[client-profile.client]
client-id="burrow-myclient"

[zookeeper]
servers=[ "zookeeper:2181" ]
timeout=6
root-path="/burrow"

[cluster.docker]
class-name="kafka"
servers=[ "kafka1:19092","kafka2:29092","kafka3:39092" ]
topic-refresh=10
offset-refresh=5

[consumer.docker]
class-name="kafka"
cluster="docker"
servers=[ "kafka1:19092","kafka2:29092","kafka3:39092" ]
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""

[consumer.zk]
class-name="kafka_zk"
cluster="docker"
servers=[ "zookeeper:2181" ]
root-path="/burrow"
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""

[httpserver.default]
address=":8000"