version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.12
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:6.2.12
    hostname: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka2:
    image: confluentinc/cp-kafka:6.2.12
    hostname: kafka2
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_INTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka3:
    image: confluentinc/cp-kafka:6.2.12
    hostname: kafka3
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092,PLAINTEXT_INTERNAL://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  burrow:
    image: "coco/burrow"
    hostname: burrow
    ports:
      - "8000:8000"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3  
    volumes:
      - ./burrow.toml:/config/burrow.toml
    restart: always

  burrow-exporter:
    image: solsson/burrow-exporter
    hostname: burrow
    ports:
      - "8080:8080"
    depends_on:
      - "burrow"
    environment:
      BURROW_ADDR: "http://burrow:8000"
      METRICS_ADDR: "0.0.0.0:8080"
      INTERVAL: "30"
      API_VERSION: "3"
    restart: always

  kafka-consumer-lag-go:
    image: kafka-consumer-lag-go
    depends_on:
      - "burrow-exporter"
    environment:
      BOOTSTRAP_SERVERS: "kafka1:19092,kafka2:29092,kafka3:39092"
